# Generated by Django 4.2.3 on 2023-07-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PfamDescription',
            fields=[
                ('domain_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pfam_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinSequence',
            fields=[
                ('protein_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_taxa_id', models.IntegerField()),
                ('organism_clade_identifier', models.CharField(max_length=255)),
                ('organism_scientific_name', models.CharField(max_length=255)),
                ('domain_description', models.CharField(max_length=255)),
                ('domain_start_coordinate', models.IntegerField()),
                ('domain_end_coordinate', models.IntegerField()),
                ('protein_length', models.IntegerField()),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioAPI.pfamdescription')),
                ('protein_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioAPI.proteinsequence')),
            ],
        ),
    ]
